### ISSUE TITLE
decide on Name and Theme of version

### ISSUE THREAD

**Issue by colleenpurcell12** [colleenpurcell12/capstoneGame#1]

**Comment by sharonghae** [comment]
Sci-Fi

resources/terrain?

**Comment by debkwon** [comment]
Solar Power (converted) (sunlight)
Ice (water)
Hematite (iron ore)
Fuel (from hydrogen in water and carbon dioxide in atmosphere)
Seeds/Crops

**Comment by debkwon** [comment]
I added styling and going to update resources: 
solar = lumber, hematite = ore, seeds = grain, fuel = wool, ice = brick
