### ISSUE TITLE
Remove redux-logger from deployed version? End users probably shouldn't be allowed to see this in their consoles.

### ISSUE THREAD

**Issue by SamiLugar** [colleenpurcell12/capstoneGame#234]

**Comment by sharonghae** [comment]
https://www.npmjs.com/package/redux-logger

Log only in development:

import thunk from 'redux-thunk';
 
const middlewares = [thunk];
 
if (process.env.NODE_ENV === `development`) {
  const createLogger = require(`redux-logger`);
  const logger = createLogger();
  middlewares.push(logger);
}
 
const store = compose(applyMiddleware(...middlewares))(createStore)(reducer);
