### ISSUE TITLE
Add firebase/redux middleware

### ISSUE THREAD

**Issue by debkwon** [colleenpurcell12/capstoneGame#76]
https://www.npmjs.com/package/firedux

**Comment by sharonghae** [comment]
https://github.com/ashaffer/redux-multi
http://jamesknelson.com/can-i-dispatch-multiple-actions-from-redux-action-creators/

**Comment by sharonghae** [comment]
Goal is to store action-creators to firebase(persistent data) and dispatch actions to local state when players enters game. 

Player enters game : we want to create a redux middleware that will dispatch array of action-creators
Game-moves: save action-creators to database
Player leaves :  turn "off" listeners to the database
